name: Swift

on: [push]

jobs:
  build:
  
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
       xcodebuild clean -workspace "HGFcollective.xcworkspace" -scheme "HGF Collective"
       cp ~/Downloads/HGFCollective/HGFcollective/GoogleService-Info.plist ~/Downloads/HGFCollective/actions-runner/_work/HGFcollective/HGFcollective/HGFcollective/GoogleService-Info.plist
       xcodebuild -workspace "HGFcollective.xcworkspace" -scheme "HGF Collective"
  lint:
  
    runs-on: self-hosted
    
    needs: build
    steps:
    - name: Lint
      run: |
       swiftlint --version
       swiftlint lint --strict --config .swiftlint.yml
